name: Auto-grades your solution

on: push

jobs:
  compiles:
    name: "Runs `make compile`"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make compile
  parts:
    name: "Grades assignment"
    runs-on: ubuntu-latest
    needs: [compiles]
    strategy:
      fail-fast: false
      matrix:
        part: [ 1, 2, 3, 4, 5, 6 ]
    steps:
      - uses: actions/checkout@master
      - run: make compile
      - name: "Downloads grader scripts"
        uses: actions/checkout@master
        with:
          repository: utah-cs4470-sp23/grader
          path: grader
      - name: "Counts total parts"
        run: echo HW_PARTS=$(make -s -C grader count-current) >> $GITHUB_ENV
      - name: Total of ${{ env.HW_PARTS }} parts
        run: true
      - name: Grade part ${{ matrix.part }}
        if: matrix.part <= env.HW_PARTS
        timeout-minutes: 5
        run: make -C grader test-current DIR=$GITHUB_WORKSPACE PART=${{ matrix.part }}

